HISTFILE=~/.histfile
HISTSIZE=3000
SAVEHIST=3000
CASE_SENSITIVE="true"

setopt autocd extendedglob nomatch notify
bindkey -e
zstyle :compinstall filename '/home/abdulrahman/.zshrc'
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select

. ~/.config/zsh/variables.zsh
. ~/.config/zsh/zinit.zsh
. ~/.config/zsh/plugins.zsh
. ~/.config/zsh/aliases.zsh
