alias :q=exit
alias ~="cd ~"
alias ..="cd .."
alias ....="cd ../.."
alias c="clear"
alias cls="clear"
alias cat="batcat"
alias ls="exa --icons --long --no-permissions --no-user --git --modified"
alias myip="curl http://ipecho.net/plain; echo"
alias py="python3"
alias tree="exa --tree --icons"
alias cd="z"
alias http="xh --follow"
alias music="ncspot"
alias weather="curl wttr.in/Egypt+Giza"
alias vim="nvim"
alias v="nvim"
function docs() { curl cheat.sh/$@ }
